name: catcher_2
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 1.0.1
homepage: https://github.com/ThexXTURBOXx/catcher_2
repository: https://github.com/ThexXTURBOXx/catcher_2
issue_tracker: https://github.com/ThexXTURBOXx/catcher_2/issues
funding:
  - https://github.com/sponsors/ThexXTURBOXx
screenshots:
  - description: "The catcher_2 logo"
    path: screenshots/logo.png
  - description: "catcher_2 in action with notifications"
    path: screenshots/1.png
  - description: "catcher_2 in action with emails"
    path: screenshots/3.png
  - description: "catcher_2 in action with dialogs"
    path: screenshots/6.png
topics:
  - analysis
  - errors
  - flutter
  - logging

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  
  flutter_mailer:
    git:
      url: https://github.com/fenil2024/flutter_mailer.git
      ref: 9b8bc28e5e1721f1b1166230ed23795606d1f5e5
  fluttertoast: ^8.2.8
  logging: ^1.3.0
  mailer: ^6.2.0
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  sentry: ^8.10.1
  universal_io: ^2.2.2
  
dev_dependencies:
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
